
name: educoach_flutter
description: EduCoach mobil uygulaması
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.1
  table_calendar: ^3.0.6
  image_picker: ^0.8.7+4
  sleek_circular_slider: ^2.0.1
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/garden.png
    - assets/tree_1.png
    - assets/tree_2.png
    - assets/tree_3.png
    - assets/tree_4.png
    - assets/shop.png
    - assets/garden_bg.png
